### ISSUE TITLE
How to use itemTemplate?

### ISSUE THREAD

**Issue by skined90** [NativeScript/nativescript-picker#13]
I found an example inside the repo how to cutomize itemTemplate but it doesn't work for me.

   ```
<PickerField hint="Click here"
                 [items]="countries"
                 [modalAnimated]="true"
                 [pickerTitle]="'Choose country'">

        <ng-template let-item="item" let-i="index">
            <StackLayout class="p-10" orientation="horizontal">
                <Label [text]="i"></Label>
                <Label [text]="item"></Label>
            </StackLayout>
        </ng-template>

    </PickerField>
```

Nothing changes inside the list.

I'm trying to implement it on Android platform Google Pixel XL real device.

Can someone help me and tell what am I doing wrong?

**Comment by VladimirAmiorkov** [comment]
Hi @skined90 ,

Do you mean that the entire `ng-template` is not used or that the `p-10` class is not applied? Can you provide me with a runnable project that shows the issue?

**Comment by skined90** [comment]
@VladimirAmiorkov Yes, exactly. Sorry but I'm not able to provide you a project. :(

**Comment by VladimirAmiorkov** [comment]
@skined90 Ok, "Yes, exactly" but to which question :) 

> Do you mean that the entire ng-template is not used or that the p-10 class is not applied?

**Comment by skined90** [comment]
@VladimirAmiorkov Oh Gosh... Sorry, didn't read well. `ng-template` is used but any css class or html is not aplied to/inside it.

**Comment by VladimirAmiorkov** [comment]
Have you read [this](https://github.com/NativeScript/nativescript-picker#styling) section regarding how the style the list view part of the plugin. Btw note that there is currently [an PR](https://github.com/NativeScript/nativescript-picker/pull/15) that would introduce breaking changes to the current way that the list view is being styled via css but that PR is still not merged and released, for more details you can follow it.

**Comment by skined90** [comment]
I've read it but with this, I'm just able to change the text colour of the items, but all other styles refer to `ListView` but not per item inside it. However, HTML is not applied. When I copy the HTML code from the [given example](https://github.com/NativeScript/nativescript-picker/blob/master/demo-angular/src/app/examples/styling/styling-example.component.html) nothing changes.

**Comment by VladimirAmiorkov** [comment]
If you cant send me a project can you send me a screenshot or video recording showing this issue. On my end that example work as expected and taping the pickers text field the list that is opened in the modal window is styled accordingly to the html declaration of the ng-template.

**Comment by skined90** [comment]
Here is the HTML 

```
<ScrollView height="100%">
    <StackLayout>
        <PickerField hint="Choose country"
                     [items]="countries"
                     pickerTitle="Choose country">

            <ng-template let-item="item" let-i="index">
                <StackLayout class="p-10" orientation="horizontal">
                    <Label [text]="i"></Label>
                    <Label [text]="item"></Label>
                </StackLayout>
            </ng-template>

        </PickerField>
    </StackLayout>
</ScrollView>
```

Here are the screenshots:

![Screenshot_1554809664](https://user-images.githubusercontent.com/11742804/55797404-9750e480-5acc-11e9-9afd-984e3f83392a.png)
![Screenshot_1554809675](https://user-images.githubusercontent.com/11742804/55797405-9750e480-5acc-11e9-8c1a-2fc64c354b52.png)

**Comment by skined90** [comment]
Okay. I realized what's the problem. My mistake, but error throwing is not so great. What happened actually is that I imported `NativeScriptPickerModule` inside my `AppModule` instead of `ChildModule` but I was still able to use the "half of a plugin".

I wouldn't realise it that I didn't have the same problem with the `RadListView` plugin.

I'm closing this issue but I think that anyone must not be able to use the component before importing module properly. I hope there is a way to implement it.

**Comment by VladimirAmiorkov** [comment]
Hi @skined90 ,

Thank you for the update. Indeed when working with any kind of UI element that has a template in Angular with lazy loaded components it is possible to hit this "not so great" behavior. Unfortunately there is nothing that we could do to handle it as the source of the issue it its the way Angular itself works when and our custom UI element register. If I can summarise it in few words what happens is that we register the RadListView or ListView tag to be associated with the actual element from NativeScript but the ng-template functionality is handled by the module by Angular, this means that the RadListView or ListView element can be used without the import of any kind of module in an NativeScript + Angular app but any kind of custom directives to that element (like its ng-template) will not work at all and will not raise any kind of error in Angular itself. We have brainstormed and discussed how we can improve this experience when an UI elements custom module is not imported but we either have to not register the html tags for RadListView and ListView which would make the need for you to manually register all if the UI elements in your app or have the current behavior.
