### ISSUE TITLE
Add "valueSelected" event to the 'PickerField'

### ISSUE THREAD

**Issue by wfe8006** [NativeScript/nativescript-picker#16]
I would like to check the selected picker value (i.e. invoke the checkTap() in the [sample](https://github.com/NativeScript/nativescript-picker/blob/master/demo-vue/app/components/ValueApis.vue) right after the modal window is closed. 

The idea is to have two pickers: namely country and state. Upon selecting a specific country value, all the states will be fetched dynamically via ajax.

Is there an event/method to do so?

**Comment by VladimirAmiorkov** [comment]
Hi @sotisoti ,

At the moment there is no event raised when a value is selected in the picker's modal window. As a workaround one possible approach is due to the fact that the Picker inherits the TextFiled class which has a textChange event, simple attach to that one, fir example using the onLoaded event if the Page:

```
<Page loaded="pageLoaded" xmlns="http://www.nativescript.org/tns.xsd" xmlns:picker="nativescript-picker">
	<GridLayout rows="50, *">
		<picker:PickerField hint="Click here" padding="10" id="myPicker"
							text="asd"
							items="{{ pickerItems }}" >
		</picker:PickerField>
	</GridLayout>
</Page>
```

```
export function pageLoaded(args: observable.EventData) {
    let page = <pages.Page>args.object;
    page.bindingContext = new GettingStartedModel();
    const picker = page.getViewById("myPicker");
    picker.on("textChange", onTextChange);
}
```

Or in an NativeScript-Angular project https://docs.nativescript.org/angular/ui/ng-ui-widgets/text-field#text-field-binding

If you would like to contribute to this repository and plugin a good place to raise this event would be [here](https://github.com/NativeScript/nativescript-picker/blob/master/src/picker.common.ts#L226).

**Comment by topclaudy** [comment]
@VladimirAmiorkov There should be a simpler way to handle events from the PickerField. I wonder why they haven't implemented any event for this widget. Without events,  it's almost useless.

**Comment by simano65** [comment]
@VladimirAmiorkov Would also be useful to have "list closed" & "list open" events, to simulate focus and blur, even when the value is not changed.

**Comment by VladimirAmiorkov** [comment]
Hi @simano65 ,

Sounds like a good feature to have. Can you open a new issue about it?

**Comment by VladimirAmiorkov** [comment]
@simano65 The above suggested events (opened & closed) have been implemented in [this PR](https://github.com/NativeScript/nativescript-picker/pull/23). You can keep track of it and look for a new version soon.

**Comment by felipebueno** [comment]
@VladimirAmiorkov thanks!

Any plans for selectedIndexChanged and/or selectedValueChanged?

**Comment by topclaudy** [comment]
When trying to implement the suggested approach in Vue, the application crashes. Here is the error message: 

`JS ERROR TypeError: undefined is not an object (evaluating 'picker.on')`

Here is the code:

```
pageLoaded(args){
                let page = args.object;
                const picker = page.getViewById("placeTypePicker");
                picker.on("textChange", onPickerTextChangeHandler);
            }
```
It seems like `getViewById` can't retrieve the element even when it's defined in the layout.

**Comment by topclaudy** [comment]
I found a solution. Wrap it in `this.$nextTick`

```
this.$nextTick(() => {
                    const picker = page.getViewById("placeTypePicker");
                    picker.on("textChange", onPickerTextChangeHandler);
                });
```

**Comment by wfe8006** [comment]
Migrating to flutter. Closing this ticket.
