### ISSUE TITLE
NativeScript events are not being called (loaded, tap ...)

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-picker#22]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 5.4.0
- Cross-platform modules: ^5.0.0
- Runtime(s): 5.4.0
- Plugin(s): 
`"nativescript-picker": "2.1.0"`

### Please, tell us how to recreate the issue in as much detail as possible. 
If you attach a handled for the loaded event of the `PickerField` it is never hit.

**Comment by zbranzov** [comment]
Released in version 2.1.1
