### ISSUE TITLE
Implement v-model for NativeScript Vue

### ISSUE THREAD

**Issue by foxted** [NativeScript/nativescript-picker#39]
Implement `v-model` for NativeScript Vue. 

Vue two-way binding on form inputs is usually done by using the attribute `v-model`, which is just a shortcut for binding a `value` prop and binding a listener for the `input` event. 

I am familiar with how to implement this in JavaScript, gave it a shot but TypeScript is foreign to me, so I couldn't figure it out. 

### Which platform(s) does your issue occur on?
- Both 
- All versions
- Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.2.0-next-2019-10-08-131118-02
- Runtime(s): iOS: 6.1.1 / Android 6.1.2
- Plugin(s): N/A

### Please, tell us how to recreate the issue in as much detail as possible. 

Ideally, we should be able to retrieve the selected value directly using the `v-model` attribute like so: 

```vue
<PickerField :hint="Country" :items="countries" valueField="key" textField="label" v-model="selectedCountry"></PickerField>
```

I'd be happy to help with the Vue specific stuff, I just need a hand on handling the TypeScript part.

**Comment by ZachPerkitny** [comment]
Was this ever implemented?
