### ISSUE TITLE
NativeScript 7 support

### ISSUE THREAD

**Issue by sivo1981** [NativeScript/nativescript-picker#50]
Currently this plugin doesn't work with NativeScript 7.

Any ETA when it will be available for latest version.

**Comment by jigsawmegs** [comment]
Any chance this will support v7 soon?

**Comment by sroy93** [comment]
Yes please! I need this to work with 7 also!

**Comment by mcgouganp** [comment]
I'll +1 this too. Considering this is a NativeScript core plugin I'm surprised it hasn't been updated to work in NS7?

**Comment by NathanaelA** [comment]
Sorry, you are all looking in the wrong spot -- https://github.com/NativeScript/plugins/tree/master/packages has the NS 7 versions of the plugins.   As you can see it is maintained for NS 7 in the plugins mono-repo.

**Comment by mcgouganp** [comment]
It’s possible that I’m mistaken, but I can’t see any plugin in that list that has the functionality of this plugin. I still think it’s been missed in the NS7 conversion.

**Comment by NathanaelA** [comment]
Hmm, you might be right -- we might have missed this plugin.   I'll reopen this issue.

**Comment by NathanWalker** [comment]
Updated and published now @nativescript/picker 3.0.0
